name: main
on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Print Vars
        run: |
          echo "printing"
          env 
      - name: Checkout Airbyte
        uses: actions/checkout@v2
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}} # always use the branch's repository
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: actions/setup-node@v1
        with:
          node-version: '14.7'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
