name: Release Open Source Airbyte
on:
  workflow_dispatch:
    inputs:
      partToBump:
        description: "Please choose the type of version upgrade : major|minor|patch"
        required: true
        default: "patch"
jobs:
  releaseAirbyte:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release Airbyte
        id: release_airbyte
        env:
          PART_TO_BUMP: ${{ github.event.inputs.partToBump }}
        run: |
          ./bump_version.sh
      - name: Find new version
        id: new_version
        run: echo '::set-output name=NEW_VERSION::$(grep VERSION version.txt | cut -d"=" -f2)'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.SUBODH_GITHUB_ACCESS_TOKEN }}
          branch: bump-version
          branch-suffix: random
          delete-branch: true
          title: Bump Airbyte ${{ github.event.inputs.partToBump }} version to ${{ steps.new_version.outputs.NEW_VERSION }}
          body: Bump Airbyte ${{ github.event.inputs.partToBump }} version to ${{ steps.new_version.outputs.NEW_VERSION }}
          commit-message: Bump Airbyte ${{ github.event.inputs.partToBump }} version to ${{ steps.new_version.outputs.NEW_VERSION }}
      - name: PR Details
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"