name: Release Open Source Airbyte
on:
  workflow_dispatch:
    inputs:
      partToBump:
        description: "Please choose the type of version upgrade : major|minor|patch"
        required: true
        default: "patch"
jobs:
  releaseAirbyte:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Save Old Version
        id: old_version
        run: |
          echo ::set-output name=OLD_VERSION::$(grep VERSION version.txt | cut -d"=" -f2)
      - name: Save GIT Revision
        id: git_revision
        run: |
          echo ::set-output name=GIT_REVISION::$(git rev-parse HEAD)
      - name: Release Airbyte
        id: release_airbyte
        env:
          PART_TO_BUMP: ${{ github.event.inputs.partToBump }}
        run: |
          ./bump_version.sh
      - name: Save New Version
        id: new_version
        run: |
          echo ::set-output name=NEW_VERSION::$(grep VERSION version.txt | cut -d"=" -f2)
      - name: Get PR Body
        id: pr_body
        run: |
          echo ::set-output name=PR_BODY::$(PAGER=cat git log 206793dfd3d863d484851f4b7fae0e87cd87a8f0..${{ steps.git_revision.outputs.GIT_REVISION }} --oneline --decorate=no)
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.SUBODH_GITHUB_ACCESS_TOKEN }}
          branch: bump-version
          branch-suffix: random
          delete-branch: true
          title: Bump Airbyte version from ${{ steps.old_version.outputs.OLD_VERSION }} to ${{ steps.new_version.outputs.NEW_VERSION }}
          body: ${{ steps.pr_body.outputs.PR_BODY }}
          commit-message: Bump Airbyte version from ${{ steps.old_version.outputs.OLD_VERSION }} to ${{ steps.new_version.outputs.NEW_VERSION }}
      - name: PR Details
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"