name: Execute 'parent' workflow

on:
  schedule:
  - cron: '5,15,25,35,45,55 * * * *'
  - cron: '*/10 * * * *'

jobs:
  deploy-frontend-dev:
    name: Call "deploy-command" workflow for frontend-dev
    if: github.event.schedule == '15,45 * * * *'
    uses: ./.github/workflows/test-deploy-command.yml
    with:
      env_name: frontend-dev
      run_type: deploy
      tests: true
  deploy-dev-2:
    name: Call "deploy-command" workflow for dev-2
    if: github.event.schedule == '0,30 * * * *'
    uses: ./.github/workflows/test-deploy-command.yml
    secrets: inherit
    with:
      env_name: dev-2
      run_type: dry
      tests: false
