name: Update 'dev-2' env cluster on daily basis

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  call-env-deploy:
    name: Call "deploy-command" workflow
    uses: ./.github/workflows/test-deploy-command.yml
