name: Update 'dev-2' env cluster on daily basis

on:
  schedule:
    - cron:  '35 16 * * *'

jobs:
  call-env-deploy:
    name: Call "deploy-command" workflow
    uses: ./.github/workflows/test-deploy-command.yml
    with:
      env_name: dev-2
      run_type: deploy
      tests_integration: false
