name: integration-test
on:
  push:
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'The comment-id of the slash command. Used to update the comment with the status.'
        required: false

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Link comment to workflow run
        if: github.event.inputs.comment-id
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            > :clock2: ${{github.event.inputs.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      - name: Print Vars
        run: |
          echo "printing"
          env 
      - name: Checkout Airbyte
        uses: actions/checkout@v2
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}} # always use the branch's repository
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: actions/setup-node@v1
        with:
          node-version: '14.7'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Add Success Comment
        if: github.event.inputs.comment-id && success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            > :white_check_mark: ${{github.event.inputs.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      - name: Add Failure Comment
        if: github.event.inputs.comment-id && !success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            > :x: ${{github.event.inputs.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
