name: Wipe Firebase and empty database tables

on:
  schedule:
    - cron: '30 12 12,13,14,15,16,17,18,22,23,24,25,26,27,28 * *'
  workflow_dispatch:
    inputs:
      env_name:
        description: "Environment Name (infra-dev, dev, dev-1, dev-2, frontend-dev, stage)"
        required: true
        default: "dev"
jobs:
  clean-db-objects:
    name: Wipe DB objects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parsing Environments Creds
        id: env-creds
        run: |-
          set -e
          case "${{ github.event.inputs.env_name }}" in
          infra-dev|dev|dev-1|dev-2|frontend-dev)
              PG_USR="${{ secrets.INFRA_DEV_PG_USR }}"
              PG_PWD="${{ secrets.INFRA_DEV_PG_PWD }}"
              PG_HOST="172.24.4.3"
              ;;
          stage)
              GCP_SA_KEY="${{ secrets.STAGE_GCP_SA_KEY }}"
              ;;
          *)
              echo "*** Unexpected env_name: ${{ github.event.inputs.env_name }} ***"
              exit 1
          esac
          echo "::set-output name=pg_usr::${PG_USR}"
          echo "::set-output name=pg_pwd::${PG_PWD}"
          echo "::set-output name=pg_host::${PG_HOST}"

      - name: Remove DB tables
        run: psql -h ${{ steps.env-creds.outputs.pg_host }} -U ${{ github.event.inputs.env_name }}-pgsql-admin -c 'SELECT TABLES;'
         env:
           PGPASSWORD: ${{ steps.env-creds.outputs.pg_pwd }}

#    - name:  Wipe DB objects
#      id: wipe
#      shell: bash
#      uses: ./.github/actions/wipe
#      with:
#        env_name: ${{ github.event.inputs.env_name }}
